### PR TITLE
[all] CI: Disable pip check due to incompatibilites between requirements

### LINKED ISSUE #5860: [all] CI is crashing due to incompatibility between requirements
CI is failing with the following logs:

```
[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
pycti==7.260224.0
pycti==7.260224.0
Installing latest version of pycti
Found existing installation: pycti 7.260224.0
Uninstalling pycti-7.260224.0:
  Successfully uninstalled pycti-7.260224.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aiobotocore 2.23.0 requires botocore<1.38.28,>=1.38.23, but you have botocore 1.42.56 which is incompatible.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
pycti @ git+https://github.com/OpenCTI-Platform/opencti.git@100bce5aa9483bd1ce70ff354df57d6b4e04c7ab#subdirectory=client-python
aiobotocore 2.23.0 has requirement botocore<1.38.28,>=1.38.23, but you have botocore 1.42.56.
Error: exit status 123
Error: exit status 123
```

link to https://github.com/OpenCTI-Platform/opencti/issues/14613

### PR DESCRIPTION
**Pull request by jabesq**
### Proposed changes

* There is currently an issue between pycti@master and some connector due to too stricts requirements in pycti

### Related issues

* Close #5860
* https://github.com/OpenCTI-Platform/opencti/issues/14613

### Checklist

- [x] I consider the submitted work as finished
- [x] I have signed my commits using GPG key.
- [ ] I tested the code for its functionality using different use cases
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### CODE REVIEW

File: run_test.sh [hunk 1]
```diff
@@ -71,17 +71,17 @@ do
   if [ -n "$project_has_sdk_dependency" ] ; then
       echo 'Installing connectors-sdk local version'
       python -m pip uninstall -y connectors-sdk
-      python -m pip install -q ./connectors-sdk
+      python -m pip install -q ./connectors-sdk   # ignore error if connectors-sdk is not installable (e.g. missing dependencies)
```
Comment (jabesq) [inline run_test.sh:74]: Comments should be removed
